class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  include PgSearch
  pg_search_scope :search_by_county, :against => [:county]
  pg_search_scope :search_by_city, :against => [:city]
  pg_search_scope :search_by_last_name, :against => [:last_name]
  pg_search_scope :search_by_town, :against => [:town]
  pg_search_scope :search_by_distributed_date, :against => [:distributed_date]
  pg_search_scope :search_by_expiration_date, :against => [:expiration_date]

  # @county_list = [
  #   'Select',
  #   'Alamance',
  #   'Alexander',
  #   'Alleghany',
  #   'Anson',
  #   'Ashe',
  #   'Avery',
  #   'Beaufort',
  #   'Bertie',
  #   'Bladen',
  #   'Brunswuick',
  #   'Buncombe',
  #   'Burke',
  #   'Cabarrus',
  #   'Caldwell',
  #   'Camden',
  #   'Carteret',
  #   'Caswell',
  #   'Catawba',
  #   'Chatham',
  #   'Cherokee',
  #   'Chowan',
  #   'Clay',
  #   'Cleveland',
  #   'Columbus',
  #   'Craven',
  #   'Cumberland',
  #   'Currituck',
  #   'Dare',
  #   'Davidson',
  #   'Davie',
  #   'Duplin',
  #   'Durham',
  #   'Edgecombe',
  #   'Forsyth',
  #   'Franklin',
  #   'Gaston',
  #   'Gates',
  #   'Graham',
  #   'Granville',
  #   'Greene',
  #   'Guilford',
  #   'Halifax',
  #   'Harnett',
  #   'Haywood',
  #   'Henderson',
  #   'Hertford',
  #   'Hoke',
  #   'Hyde',
  #   'Iredell',
  #   'Jackson',
  #   'Johnston',
  #   'Jones',
  #   'Lee',
  #   'Lenoir',
  #   'Lincoln',
  #   'McDowell',
  #   'Macon',
  #   'Madison',
  #   'Martin',
  #   'Mecklenburg',
  #   'Mitchell',
  #   'Montgomery',
  #   'Moore',
  #   'Nash',
  #   'New Hanover',
  #   'Northampton',
  #   'Onslow',
  #   'Orange',
  #   'Pamlico',
  #   'Pasquotank',
  #   'Pender',
  #   'Perquimans',
  #   'Person',
  #   'Pitt',
  #   'Polk',
  #   'Randolph',
  #   'Richmond',
  #   'Robeson',
  #   'Rockingham',
  #   'Rowan',
  #   'Rutherford',
  #   'Sampson',
  #   'Scotland',
  #   'Stanly',
  #   'Stokes',
  #   'Surry',
  #   'Swain',
  #   'Transylvania',
  #   'Tyrrell',
  #   'Union',
  #   'Vance',
  #   'Wake',
  #   'Warren',
  #   'Washington',
  #   'Watauga',
  #   'Wayne',
  #   'Wilkes',
  #   'Wilson',
  #   'Yadkin',
  #   'Yancey'
  # ]
end
